name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: workspace

    steps:
    - uses: actions/checkout@v3

    - name: ls
      run: ls /lm/tools/hw_infra
